<?php

/**
 * Implements hook_page_bottom for page bottom.
 */
function amp_pixel_page_bottom(array &$page_bottom) {

  $amp_context = \Drupal::service('router.amp_context');
  if ($amp_context->isAmpRoute()) {

    if (\Drupal::config('amp_pixel.settings')->get('amp_pixel')) {
      $domain = \Drupal::config('amp_pixel.settings')->get('amp_pixel_domain_name');
      $query_string = \Drupal::config('amp_pixel.settings')->get('amp_pixel_query_string');
      if (!empty($domain) && !empty($query_string)) {
        $subs_random = \Drupal::config('amp_pixel.settings')->get('amp_pixel_random_number');

        $subs = [
          'RANDOM' => [
            'active' => $subs_random ? TRUE : FALSE
          ]
        ];

        $amp_pixel = [
          '#theme' => 'amp_pixel',
          '#domain' => $domain,
          '#query_string' => $query_string,
          '#subs' => $subs
        ];

        $page_bottom['amp_pixel'] = $amp_pixel;
      }
    }
  }
}
